### ISSUE TITLE
add project to Projects using Docile / Lexicon

### ISSUE THREAD

**Issue by peter1000** [sam81/DetectionTheory.jl#1]
hi,

Are you still using Docile/Lexicon for documentation. If so 
I would like to add your project to [Projects using Docile / Lexicon](https://github.com/MichaelHatherly/Docile.jl#projects-using-docile--lexicon)
if that is fine with you.

Thanks.

**Comment by sam81** [comment]
sure, you can add it

**Comment by peter1000** [comment]
Do you have other project you make use of Docile or Lexicon I might add?

**Comment by sam81** [comment]
yes, there is [BrainWave.jl](https://github.com/sam81/BrainWave.jl), feel free to add it to the projects using Docile/Lexicon

**Comment by peter1000** [comment]
Great
